-- ============================================================
--  CERTIFICADOS DE LAVADO — Estructura de base de datos
-- ============================================================
--  Ejecutar en Supabase. Es SEGURO correrlo varias veces.
--
--  PASOS:
--   1. https://supabase.com/dashboard -> proyecto wvomxxaulgiwosoxcabu
--   2. Menú lateral: "SQL Editor" -> "New query"
--   3. Copiá y pegá TODO este archivo
--   4. "Run" (Ctrl+Enter). Debe decir "Success. No rows returned".
--
--  Verificar después:
--   - "Table Editor" -> "certificados": debe estar VACÍA.
--   - "Database" -> "Tables" -> certificados -> "Constraints":
--     debe figurar un UNIQUE en "numero_certificado".
--   - "Authentication" -> "Policies" -> certificados: 2 políticas
--     (cert_insert_publico, cert_select_publico).
-- ============================================================


-- ------------------------------------------------------------
-- 1. TABLA (si ya existía, esta línea no la toca)
-- ------------------------------------------------------------
create table if not exists public.certificados (
  id                  bigint generated by default as identity primary key,
  creado_en           timestamptz not null default now(),
  numero_certificado  text not null,
  fecha_lavado        date,
  placa               text,
  marca               text,
  color               text,
  conductor           text,
  licencia            text,
  empresa             text,
  telefono            text,
  producto_utilizado  text
);

-- 1b. Columnas faltantes (si la tabla ya existía con otro esquema).
alter table public.certificados add column if not exists creado_en          timestamptz not null default now();
alter table public.certificados add column if not exists numero_certificado text;
alter table public.certificados add column if not exists fecha_lavado       date;
alter table public.certificados add column if not exists placa              text;
alter table public.certificados add column if not exists marca              text;
alter table public.certificados add column if not exists color              text;
alter table public.certificados add column if not exists conductor          text;
alter table public.certificados add column if not exists licencia           text;
alter table public.certificados add column if not exists empresa            text;
alter table public.certificados add column if not exists telefono           text;
alter table public.certificados add column if not exists producto_utilizado text;


-- ------------------------------------------------------------
-- 2. LIMPIEZA DE DATOS DE PRUEBA
--    La tabla tiene filas basura del diagnóstico ("999/2099" y
--    "PRUEBA-..."). Como todavía no hay certificados reales, se
--    vacía por completo. Si YA generaste certificados de verdad,
--    borrá solo las de prueba en vez de esta línea:
--      delete from public.certificados
--      where numero_certificado = '999/2099'
--         or placa like 'PRUEBA-%';
-- ------------------------------------------------------------
truncate table public.certificados restart identity;


-- ------------------------------------------------------------
-- 3. RESTRICCIÓN UNIQUE en numero_certificado
--    Es lo que faltaba: sin esto el guardado desde la web daba
--    error 400 (código 42P10). Se agrega solo si no existe.
-- ------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.certificados'::regclass
      and contype  = 'u'
      and conname  = 'certificados_numero_certificado_key'
  ) then
    alter table public.certificados
      add constraint certificados_numero_certificado_key unique (numero_certificado);
  end if;
end $$;

-- Índice para leer rápido los certificados más recientes
create index if not exists certificados_creado_en_idx
  on public.certificados (creado_en desc);


-- ------------------------------------------------------------
-- 4. ROW LEVEL SECURITY
--    RLS activo + solo políticas de INSERT y SELECT para el rol
--    público (anon). Sin políticas de UPDATE/DELETE: el historial
--    no se puede modificar ni borrar desde la web.
-- ------------------------------------------------------------
alter table public.certificados enable row level security;

drop policy if exists "cert_insert_publico" on public.certificados;
drop policy if exists "cert_select_publico" on public.certificados;

create policy "cert_insert_publico"
  on public.certificados
  for insert
  to anon
  with check (true);

create policy "cert_select_publico"
  on public.certificados
  for select
  to anon
  using (true);
